export const FETCH_SCHEDULEGEN = 'FETCH_SCHEDULEGEN';
export const FETCH_APPTS = 'FETCH_APPTS';
export const EDIT_APPT = 'EDIT_APPT';
export const DELETE_APPT = 'DELETE_APPT';
export const FETCH_PERSONALDATA = 'FETCH_PERSONALDATA';
export const FETCH_PERSONALIMAGE = 'FETCH_PERSONALIMAGE';
export const FETCH_PERSONALPWR = 'FETCH_PERSONALPWR';